### PR TITLE
stop caring if the socket fails to close

### PR DESCRIPTION
**Pull request by kevinkjt2000**
contains suggested fix for issue #53

### CODE REVIEW

**Comment by kevinkjt2000** [comment]
@Dinnerbone could you review please?

**Comment by MarkL4YG** [comment]
it's good that you bring this up again but merging #51 would include your changes as @Klemek ran into these issues too

**Comment by kevinkjt2000** [comment]
Hmmm, it seems #51 also gets the UDP Sockets.  I missed that.  I will add it to mine too, in the case that a new feature is not wanted as an addition to a bugfix.

**Comment by MarkL4YG** [comment]
Now @Dinnerbone would only need to answer ^^

**Comment by kevinkjt2000** [comment]
@Dinnerbone?

**Comment by kevinkjt2000** [comment]
Maybe if we are good this year, Santa will give us the gift of accepting PRs

**Comment by MarkL4YG** [comment]
Or a collaborator :see_no_evil:

**Comment by kevinkjt2000** [comment]
If I had a twitter account, I would shoot dinnerbone a public tweet.

**Comment by MarkL4YG** [comment]
Well I just did that: https://twitter.com/MarkL4YG/status/929362396317175808 :P

**Comment by kevinkjt2000** [comment]
Oooooooh @Dinnerbone Wherrrrrreee are youuuuuuuuuuuuuuuuu?

**Comment by kevinkjt2000** [comment]
@Dinnerbone All I want for Chrismaaaasssssssss is youuuuuuuuuuuuuuuuuuuuu.
https://youtu.be/yXQViqx6GMY?t=38s

**Comment by MarkL4YG** [comment]
:smile: I guess I'll just fork this at some point ¯\\\_(ツ)\_/¯

**Comment by kevinkjt2000** [comment]
image

**Comment by donkeymonkey1** [comment]
Lol

**Comment by kevinkjt2000** [comment]
I'm still waiting to hear back from the pypi admins, but so far it seems like the suggested course of action would be to come up with a new name to publish to pypi with.  https://github.com/pypa/warehouse/issues/3910
Honestly, since I've been waiting a year and a half or so, I'm tempted to just give up.

**Comment by MarkL4YG** [comment]
Don't be. I'm with you. A traditional fork on GitHub and a takeover on pypi seems to be reasonable to me.
The original author is still clearly visible but project maintenance and updates can continue.

**Comment by kevinkjt2000** [comment]
I will publish a new version when I get home tonight.  I'm excited!

**Comment by MarkL4YG** [comment]
@kevinkjt2000 I am too 😉

**Pull request merged**
