### PR TITLE
Fix to allow ports > 32767

### PR DESCRIPTION
**Pull request by pangeacake**
#23

### CODE REVIEW

**Comment by lukeroge** [comment]
Can we get this merged, because it's a pretty dumb issue.

**Comment by PangeaCake** [comment]
Yeah.. really. I guess @dinnerbone's just busy

**Comment by lukeroge** [comment]
@Dinnerbone @Dinnerbone @Dinnerbone

**Comment by KamranMackey** [comment]
@Dinnerbone @Dinnerbone @Dinnerbone @Dinnerbone @Dinnerbone

**Comment by awesomebing1** [comment]
Just a bump to hopefully get @Dinnerbone's attention and get this merged.

**Comment by Scrxtchy** [comment]
So What's everyone's favourite snack?

**Comment by gnuraspberry** [comment]
@Scrxtchy raspberries apparently

**Comment by Scrxtchy** [comment]
are your raspberries open sauce?

**Comment by v0idst4r** [comment]
sry raspberries are closed sauce

**Comment by Scrxtchy** [comment]
||||
|-----|-----|---|
|Calcium|25 mg|(3%)|
|Iron|0.69 mg|(5%)|
|Magnesium|22 mg|(6%)|
|Manganese|0.67 mg|(32%)|
|Phosphorus|29 mg|(4%)|
|Potassium|151 mg|(3%)|
|Zinc|0.42 mg|(4%)|

orly?

**Comment by v0idst4r** [comment]
ur breaking the license!

**Comment by Scrxtchy** [comment]
I wonder if the licence is Free as in Free Raspberry Beer

**Comment by gnuraspberry** [comment]
Nah, seriously would like this merged and pushed to pypi.

**Comment by awesomebing1** [comment]
I think we would all like this merged. @Dinnerbone, perhaps you could merge it?

**Comment by v0idst4r** [comment]
"opened this pull request 
about 2 years ago" just make a fork man this is never going to get merged

**Comment by v0idst4r** [comment]
holy fuck i thought u were dead

On Apr 1, 2017 10:18 AM, "Dinner Bone" <notifications@github.com> wrote:

Merged #29 <https://github.com/Dinnerbone/mcstatus/pull/29>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Dinnerbone/mcstatus/pull/29#event-1025226833>, or mute
the thread

**Comment by gnuraspberry** [comment]
Yeah, I may have sent him a friendly PM on IRC.

**Comment by Dinnerbone** [comment]
Sorry. :(

Thanks for the commit!

**Comment by Scrxtchy** [comment]
You told me you sent him a pm on IRC like last week

**Comment by gnuraspberry** [comment]
This one was a bump for the pull requests :D Before I was just being annoying.

**Comment by Matthew-MK** [comment]
What is this lol

**Comment by MarkL4YG** [comment]
@Matthew-MK Serious question?

**Pull request merged**
