### PR TITLE
Add asynchronous support

### PR DESCRIPTION
**Pull request by 5IGI0**
i'm back ^^

asynchronous DNS resolving and asynchronous query isn't implemented for now, otherwise everything is done!

### CODE REVIEW

**Review by kevinkjt2000 — CHANGES_REQUESTED** [review]
This looks pretty good, but it needs automated tests in place to ensure that it stays good for the life of the project. Others could come along and accidentally break this if no tests are in place. Please look under `mcstatus/tests` for some examples. The asynchronous nature of this feature may make testing need to run async too.

**Comment by 5IGI0** [comment]
i wanted to add a test to check that the reader functions are asynchronous, but the dir() function does not return the attributes of the class '-'

image
image

**Comment by kevinkjt2000** [comment]
That's a test that I wouldn't have even thought of, very nice! Did you peek at `dir(TCPAsyncSocketConnection)`?

**Comment by 5IGI0** [comment]
> That's a test that I wouldn't have even thought of, very nice! Did you peek at `dir(TCPAsyncSocketConnection)`?
already tried, it doesin't work ;'c
but i can try to create an list of attributes outside the function

**Comment by 5IGI0** [comment]
i'm just the dumbest guy on earth, i named the test class with the same name that the connection class

**Review by kevinkjt2000 — APPROVED** [review]
Thanks for this! I'll do a version bump here momentarily and release 4.1.0

**Pull request merged**
